#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# More detailed instructions are available at:
# https://carpentries.github.io/workshop-template/customization/index.html

carpentry: "incubator"
curriculum: "FIXME"
flavor: "FIXME"
pilot: false
title: "N8 CIR WHPC HPC Carpentry Workshop"
incubator_lesson_site: "https://nclrse-training.github.io/hpc-intro-cirrus/"
incubator_pre_survey: "put the URL of your pre-workshop survey here"
incubator_post_survey: "put the URL of your post-workshop survey here"
kind: "workshop"
repository: <USERNAME>/<PROJECT>
email: "team@carpentries.org"

# Sites.
amy_site: "https://amy.carpentries.org"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
incubator: "https://github.com/carpentries-incubator/"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Surveys.
pre_survey: "https://carpentries.typeform.com/to/wi32rS?slug="
post_survey: "https://carpentries.typeform.com/to/UgVdRQ?slug="

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/

# Turn on built-in syntax highlighting.
highlighter: rouge
